package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-07-29T14:21:40.297+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "EnglishChineseSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EnglishChineseSoap {

    @WebResult(name = "TranslatorStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "TranslatorString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorString")
    @WebMethod(operationName = "TranslatorString", action = "http://WebXml.com.cn/TranslatorString")
    @ResponseWrapper(localName = "TranslatorStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorStringResponse")
    public cn.com.webxml.ArrayOfString translatorString(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "SuggestWordResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "SuggestWord", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SuggestWord")
    @WebMethod(operationName = "SuggestWord", action = "http://WebXml.com.cn/SuggestWord")
    @ResponseWrapper(localName = "SuggestWordResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.SuggestWordResponse")
    public cn.com.webxml.ArrayOfString suggestWord(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "TranslatorResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "Translator", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.Translator")
    @WebMethod(operationName = "Translator", action = "http://WebXml.com.cn/Translator")
    @ResponseWrapper(localName = "TranslatorResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorResponse")
    public cn.com.webxml.TranslatorResponse.TranslatorResult translator(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "GetMp3Result", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "GetMp3", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetMp3")
    @WebMethod(operationName = "GetMp3", action = "http://WebXml.com.cn/GetMp3")
    @ResponseWrapper(localName = "GetMp3Response", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.GetMp3Response")
    public byte[] getMp3(
        @WebParam(name = "Mp3", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String mp3
    );

    @WebResult(name = "TranslatorSentenceStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "TranslatorSentenceString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorSentenceString")
    @WebMethod(operationName = "TranslatorSentenceString", action = "http://WebXml.com.cn/TranslatorSentenceString")
    @ResponseWrapper(localName = "TranslatorSentenceStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorSentenceStringResponse")
    public cn.com.webxml.ArrayOfString translatorSentenceString(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "TranslatorReferStringResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "TranslatorReferString", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorReferString")
    @WebMethod(operationName = "TranslatorReferString", action = "http://WebXml.com.cn/TranslatorReferString")
    @ResponseWrapper(localName = "TranslatorReferStringResponse", targetNamespace = "http://WebXml.com.cn/", className = "cn.com.webxml.TranslatorReferStringResponse")
    public cn.com.webxml.ArrayOfString translatorReferString(
        @WebParam(name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );
}
