package cn.com.webxml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-07-29T14:21:40.305+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "EnglishChineseHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EnglishChineseHttpGet {

    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "TranslatorString")
    public ArrayOfString translatorString(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "SuggestWord")
    public ArrayOfString suggestWord(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "DataSet", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "Translator")
    public DataSet translator(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "base64Binary", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "GetMp3")
    public byte[] getMp3(
        @WebParam(partName = "Mp3", name = "Mp3", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String mp3
    );

    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "TranslatorSentenceString")
    public ArrayOfString translatorSentenceString(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );

    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    @WebMethod(operationName = "TranslatorReferString")
    public ArrayOfString translatorReferString(
        @WebParam(partName = "wordKey", name = "wordKey", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String wordKey
    );
}
