package cn.com.webxml;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-07-29T14:21:40.314+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "EnglishChinese", 
                  wsdlLocation = "http://fy.webxml.com.cn/webservices/EnglishChinese.asmx?wsdl",
                  targetNamespace = "http://WebXml.com.cn/") 
public class EnglishChinese extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://WebXml.com.cn/", "EnglishChinese");
    public final static QName EnglishChineseHttpPost = new QName("http://WebXml.com.cn/", "EnglishChineseHttpPost");
    public final static QName EnglishChineseSoap12 = new QName("http://WebXml.com.cn/", "EnglishChineseSoap12");
    public final static QName EnglishChineseSoap = new QName("http://WebXml.com.cn/", "EnglishChineseSoap");
    public final static QName EnglishChineseHttpGet = new QName("http://WebXml.com.cn/", "EnglishChineseHttpGet");
    static {
        URL url = null;
        try {
            url = new URL("http://fy.webxml.com.cn/webservices/EnglishChinese.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnglishChinese.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://fy.webxml.com.cn/webservices/EnglishChinese.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnglishChinese(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnglishChinese(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnglishChinese() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EnglishChinese(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EnglishChinese(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EnglishChinese(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EnglishChineseHttpPost
     */
    @WebEndpoint(name = "EnglishChineseHttpPost")
    public EnglishChineseHttpPost getEnglishChineseHttpPost() {
        return super.getPort(EnglishChineseHttpPost, EnglishChineseHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnglishChineseHttpPost
     */
    @WebEndpoint(name = "EnglishChineseHttpPost")
    public EnglishChineseHttpPost getEnglishChineseHttpPost(WebServiceFeature... features) {
        return super.getPort(EnglishChineseHttpPost, EnglishChineseHttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns EnglishChineseSoap
     */
    @WebEndpoint(name = "EnglishChineseSoap12")
    public EnglishChineseSoap getEnglishChineseSoap12() {
        return super.getPort(EnglishChineseSoap12, EnglishChineseSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnglishChineseSoap
     */
    @WebEndpoint(name = "EnglishChineseSoap12")
    public EnglishChineseSoap getEnglishChineseSoap12(WebServiceFeature... features) {
        return super.getPort(EnglishChineseSoap12, EnglishChineseSoap.class, features);
    }
    /**
     *
     * @return
     *     returns EnglishChineseSoap
     */
    @WebEndpoint(name = "EnglishChineseSoap")
    public EnglishChineseSoap getEnglishChineseSoap() {
        return super.getPort(EnglishChineseSoap, EnglishChineseSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnglishChineseSoap
     */
    @WebEndpoint(name = "EnglishChineseSoap")
    public EnglishChineseSoap getEnglishChineseSoap(WebServiceFeature... features) {
        return super.getPort(EnglishChineseSoap, EnglishChineseSoap.class, features);
    }
    /**
     *
     * @return
     *     returns EnglishChineseHttpGet
     */
    @WebEndpoint(name = "EnglishChineseHttpGet")
    public EnglishChineseHttpGet getEnglishChineseHttpGet() {
        return super.getPort(EnglishChineseHttpGet, EnglishChineseHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnglishChineseHttpGet
     */
    @WebEndpoint(name = "EnglishChineseHttpGet")
    public EnglishChineseHttpGet getEnglishChineseHttpGet(WebServiceFeature... features) {
        return super.getPort(EnglishChineseHttpGet, EnglishChineseHttpGet.class, features);
    }

}
